# Generated by Django 3.2.8 on 2023-11-21 14:40

from django.db import migrations, models
import sandwich.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=1000, verbose_name='Подзаголовок')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=sandwich.functions.get_file_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Вступление',
                'verbose_name_plural': 'Вступление',
            },
        ),
    ]
