# Generated by Django 3.2.8 on 2023-11-21 15:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import sandwich.functions


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seo'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=1000, verbose_name='Наименование в меню')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок раздела')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок "Из чего сэндвичи"')),
            ],
            options={
                'verbose_name': 'Из чего сэндвичи?',
                'verbose_name_plural': 'Из чего сэндвичи?',
            },
        ),
        migrations.AddField(
            model_name='intro',
            name='buy_button',
            field=models.CharField(default=1, max_length=1000, verbose_name='Кнопка "Купить"'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intro',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='compound_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=sandwich.functions.get_file_path, verbose_name='Изображение')),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compound_items', to='main.compound')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
