# Generated by Django 3.2.8 on 2023-11-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20231121_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compound_items',
            options={'verbose_name': 'Булочка', 'verbose_name_plural': 'Булочки'},
        ),
    ]
