# Generated by Django 3.2.8 on 2023-11-22 09:40

import ckeditor.fields
from django.db import migrations, models
import sandwich.functions


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_product_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='cooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=1000, verbose_name='Наименование в меню')),
                ('title', models.TextField(blank=True, verbose_name='Заголовок')),
                ('sale_button', models.CharField(blank=True, max_length=1000, verbose_name='Кнопка "Позвонить в отдел продаж"')),
                ('posm_title', models.CharField(blank=True, max_length=1000, verbose_name='Заголовок "Дарим POSM материалы"')),
                ('discuss_title', models.CharField(blank=True, max_length=1000, verbose_name='Заголовок "Обсудим с вами"')),
                ('discuss_list', ckeditor.fields.RichTextField(blank=True, verbose_name='Список из "Обсудим с вами"')),
                ('image', models.ImageField(help_text='Формат файла: JPG, JPEG, PNG или WEBP. Ограничение размера: 3 Мбайт.', upload_to=sandwich.functions.get_file_path, verbose_name='Изображение')),
            ],
        ),
    ]
