# Generated by Django 3.2.8 on 2023-11-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cooperation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperation',
            options={'verbose_name': 'Сотрудничество', 'verbose_name_plural': 'Сотрудничество'},
        ),
    ]
