# Generated by Django 3.2.8 on 2023-11-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_cooperation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок "Работа у нас"')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('send_button', models.CharField(max_length=1000, verbose_name='Кнопка "Отправить"')),
            ],
            options={
                'verbose_name': 'Работа у нас / Вакансии',
                'verbose_name_plural': 'Работа у нас / Вакансии',
            },
        ),
    ]
