# Generated by Django 3.2.8 on 2023-11-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compound_items',
            options={'ordering': ['order'], 'verbose_name': 'Булочка', 'verbose_name_plural': 'Булочки'},
        ),
    ]
