# Generated by Django 3.2.8 on 2023-11-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_contacts_menu_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='instagram',
            field=models.URLField(default=1, verbose_name='Ссылка на Instagram'),
            preserve_default=False,
        ),
    ]
