# Generated by Django 3.2.8 on 2023-11-23 14:00

from django.db import migrations, models
import sandwich.functions


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contacts_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound_items',
            name='image',
            field=models.ImageField(upload_to=sandwich.functions.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='image',
            field=models.ImageField(upload_to=sandwich.functions.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='image',
            field=models.ImageField(upload_to=sandwich.functions.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product_items',
            name='image',
            field=models.ImageField(upload_to=sandwich.functions.get_file_path, verbose_name='Изображение'),
        ),
    ]
