# Generated by Django 3.2.8 on 2023-11-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20231123_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
