# Generated by Django 3.2.8 on 2023-11-23 16:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_compound_items_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound_items',
            name='color',
        ),
        migrations.AddField(
            model_name='product_items',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
