# Generated by Django 3.2.8 on 2023-11-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20231123_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_items',
            options={'ordering': ['order'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
