# Generated by Django 3.2.8 on 2023-11-23 16:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_product_items_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_items',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None, verbose_name='Цвет'),
        ),
    ]
