# Generated by Django 3.2.8 on 2023-11-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_product_items_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='sale_phone',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Телефон отдела продаж'),
        ),
    ]
