# Generated by Django 3.2.8 on 2023-11-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_cooperation_sale_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='discuss_list',
            field=models.TextField(blank=True, verbose_name='Список из "Обсудим с вами"'),
        ),
    ]
