# Generated by Django 3.2.8 on 2023-11-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_vacancy_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='footer_title',
            field=models.CharField(default=1, max_length=1000, verbose_name='Наименование в нижней части сайта (ингредиенты)'),
            preserve_default=False,
        ),
    ]
