# Generated by Django 3.2.8 on 2023-11-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_compound_footer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='footer_title',
            field=models.CharField(default=1, max_length=1000, verbose_name='Наименование в нижней части сайта (Продукты)'),
            preserve_default=False,
        ),
    ]
