# Generated by Django 3.2.8 on 2023-11-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_product_footer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='title_call',
            field=models.CharField(default=1, max_length=1000, verbose_name='Заголовок "Хочу позвонить"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_client',
            field=models.CharField(default=1, max_length=1000, verbose_name='Заголовок "Оптовым клиентам"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_email',
            field=models.CharField(default=1, max_length=1000, verbose_name='Заголовок "Связаться с нами"'),
            preserve_default=False,
        ),
    ]
