# Generated by Django 3.2.8 on 2023-11-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20231124_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='general',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_title_cert', models.CharField(max_length=1000, verbose_name='Наименование в меню нижней части сайта "Сертификаты"')),
                ('title_work', models.CharField(max_length=1000, verbose_name='Заголовок "Мы работаем"')),
                ('work_days', models.CharField(max_length=1000, verbose_name='Дни работы')),
                ('work_time', models.CharField(max_length=1000, verbose_name='Часы работы')),
                ('org_name', models.CharField(max_length=1000, verbose_name='Наименование организации (ОсОО)')),
                ('brandbook_button', models.CharField(max_length=1000, verbose_name='Кнопка "Брендбук"')),
                ('title_media', models.CharField(max_length=1000, verbose_name='Заголовок "Для медийного сотрудничества"')),
                ('title_confidence', models.CharField(max_length=1000, verbose_name='Заголовок "Соглашение о конфиденциальности"')),
                ('up_button', models.CharField(max_length=1000, verbose_name='Кнопка "Наверх"')),
            ],
            options={
                'verbose_name': 'Общее',
                'verbose_name_plural': 'Общее',
            },
        ),
    ]
