# Generated by Django 3.2.8 on 2023-11-24 09:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='discuss_list',
            field=ckeditor.fields.RichTextField(verbose_name='Список из "Обсудим с вами"'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='discuss_title',
            field=models.CharField(max_length=1000, verbose_name='Заголовок "Обсудим с вами"'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='posm_title',
            field=models.CharField(max_length=1000, verbose_name='Заголовок "Дарим POSM материалы"'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='sale_button',
            field=models.CharField(max_length=1000, verbose_name='Кнопка "Позвонить в отдел продаж"'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='sale_phone',
            field=models.CharField(max_length=1000, verbose_name='Телефон отдела продаж'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
    ]
