# Generated by Django 3.2.8 on 2023-11-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20231124_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='buy_button_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Кнопка "Купить"'),
        ),
        migrations.AddField(
            model_name='intro',
            name='buy_button_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Кнопка "Купить"'),
        ),
        migrations.AddField(
            model_name='intro',
            name='buy_button_kz',
            field=models.CharField(max_length=1000, null=True, verbose_name='Кнопка "Купить"'),
        ),
        migrations.AddField(
            model_name='intro',
            name='buy_button_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Кнопка "Купить"'),
        ),
        migrations.AddField(
            model_name='intro',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='intro',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='intro',
            name='description_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='intro',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='intro',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='intro',
            name='subtitle_ky',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='intro',
            name='subtitle_kz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='intro',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='intro',
            name='title_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='intro',
            name='title_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='intro',
            name='title_kz',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='intro',
            name='title_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок'),
        ),
    ]
