# Generated by Django 3.2.8 on 2023-11-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20231124_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intro',
            old_name='buy_button_kk',
            new_name='buy_button_kz',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='description_kk',
            new_name='description_kz',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='subtitle_kk',
            new_name='subtitle_kz',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='title_kk',
            new_name='title_kz',
        ),
        migrations.RenameField(
            model_name='seo',
            old_name='description_kk',
            new_name='description_kz',
        ),
        migrations.RenameField(
            model_name='seo',
            old_name='keywords_kk',
            new_name='keywords_kz',
        ),
        migrations.RenameField(
            model_name='seo',
            old_name='title_kk',
            new_name='title_kz',
        ),
    ]
