# Generated by Django 3.2.8 on 2023-11-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20231124_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='footer_title_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Наименование в нижней части сайта (ингредиенты)'),
        ),
        migrations.AddField(
            model_name='compound',
            name='footer_title_kk',
            field=models.CharField(max_length=1000, null=True, verbose_name='Наименование в нижней части сайта (ингредиенты)'),
        ),
        migrations.AddField(
            model_name='compound',
            name='footer_title_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Наименование в нижней части сайта (ингредиенты)'),
        ),
        migrations.AddField(
            model_name='compound',
            name='footer_title_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Наименование в нижней части сайта (ингредиенты)'),
        ),
        migrations.AddField(
            model_name='compound',
            name='title_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Из чего сэндвичи"'),
        ),
        migrations.AddField(
            model_name='compound',
            name='title_kk',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Из чего сэндвичи"'),
        ),
        migrations.AddField(
            model_name='compound',
            name='title_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Из чего сэндвичи"'),
        ),
        migrations.AddField(
            model_name='compound',
            name='title_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Из чего сэндвичи"'),
        ),
    ]
