# Generated by Django 3.2.8 on 2023-11-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20231124_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound_items',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='compound_items',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='compound_items',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='compound_items',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='compound_items',
            name='title_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='compound_items',
            name='title_kk',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='compound_items',
            name='title_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='compound_items',
            name='title_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок'),
        ),
    ]
