# Generated by Django 3.2.8 on 2023-11-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20231124_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperation',
            name='sale_phone_en',
        ),
        migrations.RemoveField(
            model_name='cooperation',
            name='sale_phone_kk',
        ),
        migrations.RemoveField(
            model_name='cooperation',
            name='sale_phone_ky',
        ),
        migrations.RemoveField(
            model_name='cooperation',
            name='sale_phone_ru',
        ),
    ]
