# Generated by Django 3.2.8 on 2023-11-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20231124_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='menu_title_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Наименование в меню'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='menu_title_kk',
            field=models.CharField(max_length=1000, null=True, verbose_name='Наименование в меню'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='menu_title_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Наименование в меню'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='menu_title_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Наименование в меню'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_call_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Хочу позвонить"'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_call_kk',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Хочу позвонить"'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_call_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Хочу позвонить"'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_call_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Хочу позвонить"'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_client_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Оптовым клиентам"'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_client_kk',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Оптовым клиентам"'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_client_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Оптовым клиентам"'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_client_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Оптовым клиентам"'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_email_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Связаться с нами"'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_email_kk',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Связаться с нами"'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_email_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Связаться с нами"'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_email_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Связаться с нами"'),
        ),
    ]
