# Generated by Django 3.2.8 on 2023-11-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20231124_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='menu_title_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Наименование в меню'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='menu_title_kk',
            field=models.CharField(max_length=1000, null=True, verbose_name='Наименование в меню'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='menu_title_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Наименование в меню'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='menu_title_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Наименование в меню'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='send_button_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Кнопка "Отправить"'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='send_button_kk',
            field=models.CharField(max_length=1000, null=True, verbose_name='Кнопка "Отправить"'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='send_button_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Кнопка "Отправить"'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='send_button_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Кнопка "Отправить"'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Работа у нас"'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_kk',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Работа у нас"'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Работа у нас"'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Заголовок "Работа у нас"'),
        ),
    ]
