# Generated by Django 3.2.8 on 2023-11-24 14:47

from django.db import migrations, models
import sandwich.functions


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20231124_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(upload_to=sandwich.functions.get_file_path, verbose_name='Изображение'),
        ),
    ]
