# Generated by Django 3.2.8 on 2023-11-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20231124_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_items',
            name='spicy_boolean',
            field=models.BooleanField(blank=True, default=False, verbose_name='Пометка для острых продуктов'),
        ),
    ]
