# Generated by Django 3.2.8 on 2023-11-25 05:12

from django.db import migrations, models
import sandwich.functions


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_product_items_spicy_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_items',
            name='image',
            field=models.ImageField(blank=True, upload_to=sandwich.functions.get_file_path, verbose_name='Изображение'),
        ),
    ]
