# Generated by Django 3.2.8 on 2023-11-25 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_product_items_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_items',
            name='product',
        ),
    ]
