# Generated by Django 3.2.8 on 2023-11-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_remove_product_items_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_items',
            options={'ordering': ['order'], 'verbose_name': 'Продукция (товары)', 'verbose_name_plural': 'Продукция (товары)'},
        ),
    ]
