# Generated by Django 3.2.8 on 2023-11-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_product_items_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='ФИО')),
                ('year', models.DateField(verbose_name='Дата')),
                ('phone', models.CharField(max_length=1000, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
