# Generated by Django 3.2.8 on 2023-11-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20231125_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_form',
            old_name='name',
            new_name='form_name',
        ),
        migrations.RenameField(
            model_name='model_form',
            old_name='phone',
            new_name='form_phone',
        ),
    ]
