# Generated by Django 3.2.8 on 2023-11-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_model_form_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_form',
            old_name='year',
            new_name='date',
        ),
    ]
