# Generated by Django 3.2.8 on 2023-12-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_model_form_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='ФИО')),
                ('year', models.CharField(max_length=1000, verbose_name='Год рождения')),
                ('phone', models.CharField(max_length=1000, verbose_name='Номер телефона')),
                ('department', models.CharField(max_length=1000, verbose_name='Укажите отдел')),
            ],
            options={
                'verbose_name': 'Переводы для формы',
                'verbose_name_plural': 'Переводы для формы',
            },
        ),
    ]
