# Generated by Django 3.2.8 on 2023-12-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='department_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='departments',
            name='department_kk',
            field=models.CharField(max_length=1000, null=True, verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='departments',
            name='department_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='departments',
            name='department_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Отдел'),
        ),
    ]
