# Generated by Django 3.2.8 on 2023-12-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20231204_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_form',
            name='department',
            field=models.CharField(default='1', max_length=1000, verbose_name='Отдел'),
        ),
    ]
