# Generated by Django 3.2.8 on 2023-12-04 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_alter_model_form_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_form',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.departments', verbose_name='Отдел'),
        ),
    ]
