# Generated by Django 3.2.8 on 2023-12-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_alter_model_form_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='error_form',
            field=models.CharField(default=1, max_length=1000, verbose_name='Сообщение об ошибке отправки формы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='general',
            name='success_form',
            field=models.CharField(default=1, max_length=1000, verbose_name='Сообщение об успешной отправке формы'),
            preserve_default=False,
        ),
    ]
