# Generated by Django 3.2.8 on 2023-12-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_auto_20231204_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='error_form_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Сообщение об ошибке отправки формы'),
        ),
        migrations.AddField(
            model_name='general',
            name='error_form_kk',
            field=models.CharField(max_length=1000, null=True, verbose_name='Сообщение об ошибке отправки формы'),
        ),
        migrations.AddField(
            model_name='general',
            name='error_form_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Сообщение об ошибке отправки формы'),
        ),
        migrations.AddField(
            model_name='general',
            name='error_form_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Сообщение об ошибке отправки формы'),
        ),
        migrations.AddField(
            model_name='general',
            name='success_form_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Сообщение об успешной отправке формы'),
        ),
        migrations.AddField(
            model_name='general',
            name='success_form_kk',
            field=models.CharField(max_length=1000, null=True, verbose_name='Сообщение об успешной отправке формы'),
        ),
        migrations.AddField(
            model_name='general',
            name='success_form_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Сообщение об успешной отправке формы'),
        ),
        migrations.AddField(
            model_name='general',
            name='success_form_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Сообщение об успешной отправке формы'),
        ),
    ]
